plugins:
  - serverless-dynamodb-local

service: pair-api

provider:
  name: aws #Define the cloud provider to use
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: Allow
      Action: # Gives permission to DynamoDB tables in a specific region
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  app:
    handler: app.handler
    events: #Define the events that trigger the lambda
      - http:
          method: GET
          path: /pair/wine
          private: false
resources:
  Resources:
    WineDynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          # TODO: build schema that reflects wine bottle
          - AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: WineDynamoDbTable
